---
on:
  push:
    branches:
    - "**"
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04

    steps:
    - name: checkout code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # 4.1.7

    - name: install pnpm
      uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # 4.0.0

    - name: install node
      uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # 4.0.3
      with:
        node-version: v18.7.0
        cache: pnpm

    - name: install dependencies
      run: pnpm i

    - name: build
      run: pnpm run build


  lint:
    name: lint
    runs-on: ubuntu-22.04

    steps:
    - name: checkout code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # 4.1.7

    - name: install pnpm
      uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # 4.0.0

    - name: install node
      uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # 4.0.3
      with:
        node-version: v18.7.0
        cache: pnpm

    - name: install dependencies
      run: pnpm i

    - name: lint
      run: pnpm run lint

  deploy:
    name: deploy to fly.io
    runs-on: ubuntu-22.04
    needs:
    - build
    # - lint
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

    steps:
    - name: checkout code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # 4.1.7

    - name: setup flyctl
      uses: superfly/flyctl-actions/setup-flyctl@fc53c09e1bc3be6f54706524e3b82c4f462f77be # 1.5

    - name: deploy
      run: flyctl deploy --remote-only --no-cache
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
