---
on:
  push:
    branches:
    - "**"
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04

    steps:
    - name: checkout code
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # 3.0.2

    - name: install pnpm
      uses: pnpm/action-setup@35ab4267a1a21c8e8cb1c087cf1642e891ff57bd # v2.2.1

    - name: install node
      uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # 3.3.0
      with:
        node-version: v18.7.0
        cache: pnpm

    - name: install dependencies
      run: pnpm i

    - name: build
      run: pnpm run build


  lint:
    name: lint
    runs-on: ubuntu-22.04

    steps:
    - name: checkout code
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # 3.0.2

    - name: install pnpm
      uses: pnpm/action-setup@35ab4267a1a21c8e8cb1c087cf1642e891ff57bd # v2.2.1

    - name: install node
      uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # 3.3.0
      with:
        node-version: v18.7.0
        cache: pnpm

    - name: install dependencies
      run: pnpm i

    - name: lint
      run: pnpm run lint

  push-container:
    name: push container to fly.io
    runs-on: ubuntu-22.04
    needs:
    - build
    - lint
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

    steps:
    - name: checkout code
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # 3.0.2

    - name: setup flyctl
      uses: superfly/flyctl-actions/setup-flyctl@master

    - name: deploy
      run: flyctl deploy --remote-only --no-cache
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
