---
on:
  push:
    branches-ignore:
    - "deploy"
    - "deploy2"
  pull_request:

name: ci
jobs:
  build:
    name: build/lint
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        project:
        - djs
        - djs2
        - droff

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: "16.8.0"

    - name: install npm (known, consistent version)
      run: npm i -g npm@7.21.0

    - name: install dependencies
      run: npm ci

    - name: build typescript
      run: npm run build:${{ matrix.project }}

    - name: lint typescript
      run: npm run lint:${{ matrix.project }}
