---
on:
  push:
    branches-ignore:
    - "deploy"
    - "deploy2"
  pull_request:

name: ci
jobs:
  build:
    name: build/lint
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        node:
          - 14
          - 16
    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: install dependencies
      run: npm ci

    - name: build typescript
      run: npm run build

    - name: lint typescript
      run: npm run lint
